name: Evolute Proxy
version: "1.0.43"
slug: evolute_proxy
description: Evolute telematics proxy API for Home Assistant
url: "https://github.com/Tamahome-M/evolute_proxy"
startup: application
boot: auto
init: false
arch:
  - aarch64
  - amd64
ports:
  12321/tcp: 12321
ports_description:
  12321/tcp: Evolute Proxy API
options:
  car_id: ""
  api_key: "changeme"
  api_key_rw: "changeme_rw"
  access_token: ""
  refresh_token: ""
  timeout: 60
  refresh_interval: 600
  sensors_refresh_interval: 120
  json_sub: ".sensors"
  debug: false
schema:
  car_id: str
  api_key: str
  api_key_rw: str
  access_token: str
  refresh_token: str
  timeout: int(5,300)
  refresh_interval: int(30,3600)
  sensors_refresh_interval: int(5,3600)
  json_sub: str
  debug: bool
